### PR TITLE
#635 Select wrapper BI style

### LINKED ISSUE #635: [BUG] Align Select input style with BI one
**Describe the bug**
The `react-select` `Select` component used in the toolkit should be aligned with the styling with the BI one.

In particular this css fix should be applied (either via CSS override or via JS-in-CSS):

```jsx
<Select
...
styles={{
  container: (provided) => ({...provided, height: '2.5rem'}),
  valueContainer: (provided) => ({...provided, height: '2.5rem'}),
  control: (provided) => ({...provided, height: '2.5rem'}),
  }}
.../>
```

### PR DESCRIPTION
**Pull request by ewedlund**
Fixes #635

#### PR Checklist

- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

(did not find where to add tests, and running `yarn test` fails on different components)

#### Short description of what this resolves:
Added a wrapper to enable a Bootstrap Italia style Select, without the need to copy code from the stories. Also improved the styling to be more similar to Bootstrap Italia

#### Changes proposed in this pull request:

- Added Select component
- Modified Examples to user the new Component

I do not have much experience in React and especially PropTypes so I apologize for any mistakes.

### CODE REVIEW

File: src/components/Select/Select.js [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+const propTypes = {
+  ...SelectBase.propTypes,
+  icon: PropTypes.bool,
+  clearText: PropTypes.string
+}
+
+const defaultProps = {
+  ...SelectBase.defaultProps,
+  icon: false,
+  clearText: 'Cancella'
```
Comment (dej611) [inline src/components/Select/Select.js:15]: Probably `"Annulla"` fits better here

**Review by dej611 — CHANGES_REQUESTED** [review]
Hi @ewedlund!

Thanks for your contribution. 🎉 

The PR looks good, there's only a minor change I'd suggest to make it work right now. This is a good first step for this component integratin in the toolkit.

**Review by dej611 — APPROVED** [review]
